# Generated by Django 5.0.6 on 2026-03-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companyusermembership',
            index=models.Index(fields=['company', 'user'], name='company_mem_company_b0a048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyusermembership',
            unique_together={('company', 'user')},
        ),
    ]
