# Generated by Django 5.0.6 on 2026-03-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_is_active_remove_company_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyusermembership',
            new_name='company_mem_company_c271f1_idx',
            old_name='company_mem_company_b0a048_idx',
        ),
        migrations.AlterModelTable(
            name='companyusermembership',
            table='company_membership',
        ),
    ]
